name: Full Test

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
        django-version: ['4.2', '5.1', '5.2']
        pydantic-version: ['2.5', '2.6', '2.7', '2.8', '2.9', '2.10', '2.11']
        exclude:
          # Pydantic 2.5 supports 3.8-3.13
          # Pydantic 2.6 supports 3.8-3.12
          - pydantic-version: '2.6'
          - python-version: '3.13'
          # Pydantic 2.7 supports 3.8-3.12
          - pydantic-version: '2.7'
            python-version: '3.13'
          # Pydantic 2.11 supports 3.9-3.13
          - pydantic-version: '2.11'
            python-version: '3.8'
          # Django 4.2 supports 3.8-3.12
          - django-version: '4.2'
            python-version: '3.13'
          # Django 5.1 supports 3.10-3.13
          - django-version: '5.1'
            python-version: '3.8'
          - django-version: '5.1'
            python-version: '3.9'
          # Django 5.2 supports 3.10-3.13
          - django-version: '5.2'
            python-version: '3.8'
          - django-version: '5.2'
            python-version: '3.9'
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install core
        run: pip install --pre "Django~=${{ matrix.django-version }}".0 "pydantic~=${{ matrix.pydantic-version }}.0"
      - name: Install tests
        run: pip install pytest pytest-asyncio pytest-django psycopg2-binary coverage pytest-cov
      - name: Format test name
        id: name
        run: |
          echo "name=py${{ matrix.python-version }}.dj${{ matrix.django-version }}.pd${{ matrix.pydantic-version }}" | sed -e "s/<//g" -e "s/>//g" >> "$GITHUB_OUTPUT"
      - name: Test
        run: COVERAGE_FILE=".coverage.${{ steps.name.outputs.name }}" pytest --junit-xml="pytest-${{ steps.name.outputs.name }}}.xml" --cov=ninja --cov-fail-under=0
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v5
        with:
          include-hidden-files: true
          name: Test Results (${{ steps.name.outputs.name }})
          path: |
            pytest-*.xml
            .coverage.*

  coverage:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      checks: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install Flit
        run: pip install flit "django>=5.0"
      - name: Install Dependencies
        run: flit install --symlink
      - name: Download Coverage Artifacts
        uses: actions/download-artifact@v7
        with:
          path: artifacts
      - name: Combine Coverage Artifacts
        run: |
          cp artifacts/*/.coverage.* .
          coverage combine
          coverage xml --fail-under=0
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          files: |
            artifacts/**/*.xml
      - name: Pytest coverage comment
        uses: orgoro/coverage@v3.2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: '1.0'
          thresholdModified: '1.0'
          thresholdNew: '1.0'
      - name: Check minimum coverage
        run: |
          coverage report --fail-under=100

  codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.9
      - name: Install Flit
        run: pip install flit
      - name: Install Dependencies
        run: flit install --symlink
      - name: Ruff format
        run: ruff format --preview --check ninja tests
      - name: Ruff lint
        run: ruff check --preview ninja tests
      - name: mypy
        run: mypy ninja tests/mypy_test.py
